#[doc = "Register `FSCR` reader"]
pub struct R(crate::R<FSCR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<FSCR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<FSCR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<FSCR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `FSCR` writer"]
pub struct W(crate::W<FSCR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<FSCR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<FSCR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<FSCR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `FSCR` reader - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
pub struct FSCR_R(crate::FieldReader<u32, u32>);
impl FSCR_R {
    pub(crate) fn new(bits: u32) -> Self {
        FSCR_R(crate::FieldReader::new(bits))
    }
}
impl core::ops::Deref for FSCR_R {
    type Target = crate::FieldReader<u32, u32>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
#[doc = "Field `FSCR` writer - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
pub struct FSCR_W<'a> {
    w: &'a mut W,
}
impl<'a> FSCR_W<'a> {
    #[doc = r"Writes raw bits to the field"]
    #[inline(always)]
    pub unsafe fn bits(self, value: u32) -> &'a mut W {
        self.w.bits = (self.w.bits & !0xffff_ffff) | (value as u32 & 0xffff_ffff);
        self.w
    }
}
impl R {
    #[doc = "Bits 0:31 - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
    #[inline(always)]
    pub fn fscr(&self) -> FSCR_R {
        FSCR_R::new((self.bits & 0xffff_ffff) as u32)
    }
}
impl W {
    #[doc = "Bits 0:31 - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
    #[inline(always)]
    pub fn fscr(&mut self) -> FSCR_W {
        FSCR_W { w: self }
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Formatter Synchronization Counter\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [fscr](index.html) module"]
pub struct FSCR_SPEC;
impl crate::RegisterSpec for FSCR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [fscr::R](R) reader structure"]
impl crate::Readable for FSCR_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [fscr::W](W) writer structure"]
impl crate::Writable for FSCR_SPEC {
    type Writer = W;
}
#[doc = "`reset()` method sets FSCR to value 0"]
impl crate::Resettable for FSCR_SPEC {
    #[inline(always)]
    fn reset_value() -> Self::Ux {
        0
    }
}
